"""FlowChartCharter core — execution-and-quality-first multi-agent state-charts."""

from .metrics import ExecutionMetrics
from .agents import Agent, BossAgent, AgentStatus, WorkerNode
from .blackboard import Blackboard, TaskRequest
from .charter import FlowUnit, Charter, CharterState
from .system import FlowChartCharterSystem
from .fitness import (
    fitness,
    fitness_components,
    speed_score,
    token_bloat_penalty,
    reference_node_fitness,
    risk_from_fitness,
    DEFAULT_ALPHA,
    DEFAULT_BETA,
    DEFAULT_GAMMA,
    DEFAULT_DELTA,
    COST_NORM,
    INDUSTRY_BENCHMARK,
)
from .vectors import (
    StrategyVector,
    BudgetVector,
    GovernanceVector,
    OpsVector,
    RhythmAudit,
    validate_executive_payload,
)
from .executive import (
    CEOAgent,
    CFOAgent,
    BoardAgent,
    RhythmValidatorAgent,
    ExecutiveBoard,
)
from .knowledge_graph import KnowledgeGraph, build_ontology
from .live_model import LiveModel
from .llm_bridge import detect_live_provider, LLMBridge, LLMBridgeConfig
from .stranger_receipt import issue_receipt, verify_receipt, verify_chain
from .charter_memory import (
    TextUnit,
    ProposedGraph,
    VerifyVerdict,
    MergeReceipt,
    extract_triples,
    verify_extraction,
    ingest_text,
    run_reindex_loop,
    bind_episode,
)
from .foundations import (
    FOUNDATIONS,
    foundations_table,
    blueprint_export,
    FLOW_UNIT_BLUEPRINT,
)
from .quantum import (
    QuantumRouter,
    quantum_path_select,
    build_superposition,
    measure,
    reinforce,
    entanglement_score,
    contextual_entropy,
    apply_cfo_budget_matrix,
    SuperpositionState,
    PathAmplitude,
    MeasurementRecord,
    DEFAULT_PATHS,
    PATH_STANDARD,
    PATH_CLEANSING,
    PATH_LITE,
)
from .synergy import (
    synergy_score,
    structural_divergence,
    handoff_synergy,
    mean_pair_synergy,
)
from .skills import (
    AgentSkillRuntime,
    MuscleMemoryStore,
    MuscleMemoryRecord,
    RosterAction,
    init_boss_agent,
)
from .prompts import (
    BOSS_AGENT_SYSTEM_PROMPT,
    BOSS_ACKNOWLEDGEMENT,
    AGENT_SKILL_SCHEMAS,
)
from .reference_engine import (
    TypedFlowUnit,
    AgentFitness,
    ReferenceQuantumRouter,
    WorkerAgent,
    BossAgent as ReferenceBossAgent,
    CFOHaltError,
    default_playbook,
    run_reference_simulation,
    apply_reference_telemetry,
)
from .muscle_memory import (
    ExecutionMemoryRecord,
    MuscleMemoryVectorDB,
    encode_state,
    cosine_similarity,
    seed_legacy_refactor,
    run_muscle_memory_simulation,
)
from .survival import (
    SurvivalStatus,
    GenerationParameters,
    LedgerEntry,
    TelemetryLedger,
    LeanRehireDecision,
    build_worker_system_prompt,
    generation_params_for_risk,
    risk_from_ledger,
    lean_rehire_check,
    should_fire_from_ledger,
)
from .elastic import ElasticRequisitionBoard, PhantomRecord
from .living_playbook import (
    LivingPlaybook,
    AscendedMemoryRecord,
    AbstractedKPIs,
    seed_living_playbook,
    objective_signature_from_payload,
    capability_map_from_path,
)
from .llm_bridge import LLMBridge, LLMNodeOutput, LLMBridgeConfig, SamplingParams, ProviderUsage, resolve_provider_key
from .simulation_sandbox import (
    SimulationSandbox,
    ScenarioSandbox,
    run_phase2_sandbox,
)
from .observability import get_metrics_hub, MetricsHub
from .state_persister import StatePersister, get_persister
from .security import require_admin_key, ensure_admin_key_on_boot
from .playbook_compiler import (
    PlaybookCompiler,
    CompiledPlaybook,
    compile_playbook,
    generate_pydantic_model,
    hydrate_system,
    run_compiled_playbook,
)
from .production import (
    LLMExecutionClient,
    LLMExecutionRequest,
    LLMExecutionResponse,
    FlowUnitResultSchema,
    validate_llm_output,
    ProductionMuscleMemory,
    EmbeddingProvider,
    run_workers_parallel,
    WorkerTask,
)
from .analytics import (
    AnalyticsChief,
    RosterRecommendationDossier,
    DailyTelemetrySnapshot,
    AgentTrend,
    CheatCodeExtraction,
    WORKWEEK_DAYS,
)
from .hybrid_router import HybridBossRouter, RouteLane, RouteDecision
from .multi_hop_reasoner import (
    MultiHopReasoner,
    HopSchema,
    MultiHopResultSchema,
)
from .synthesis_squad import (
    LazyGlobalSynthesisSquad,
    GlobalSynthesisReport,
    CommunityMapResult,
    SynthesisSquadMember,
)
from .swarm_manager import (
    SwarmManager,
    SwarmItemSchema,
    SwarmItemResultSchema,
    SwarmReportSchema,
    TokenLedger,
)

from .secret_vault import SecretScrubber, StatePersisterVault, scrub_payload
from .tenant import (
    TenantNamespacedEngine,
    TenantRegistry,
    get_tenant_registry,
    resolve_tenant_id,
)
from .rhythm_gate import (
    RhythmViolationError,
    ForceQualityForbidden,
    EvidenceBundle,
    build_rhythm_audit,
    independent_audit,
    earned_quality,
    collect_evidence,
    enforce_rhythm_or_raise,
    marker_for_unit,
)
from .llm_providers import list_providers, run_golden_evals, DEFAULT_GOLDEN_TASKS
from .live_golden import run_live_goldens
from .retrieval_port import RetrievalPort, RetrievalResult, RetrievalHit
from .harness import HarnessKernel, KillSwitch, KillSwitchError, ToolPort
from .execution_sandbox import ExecutionSandbox, SandboxPolicy
from .durable_notebook import DurableNotebook
from .kill_law import bind as bind_kill_law
from .kill_law import refuse_side_effect

from .charter_synthesizer import (
    CharterSynthesizer,
    CharterDraft,
    CharterDraftStatus,
    SynthesizedCharterSchema,
    audit_cfo_ceiling,
    seed_synthesis_memories,
    validate_synthesized_unit,
)
from .action_units import (
    ActionUnit,
    ActionUnit_SlackWebhook,
    ActionUnit_GitHubPR,
    ActionResult,
    SlackWebhookPayload,
    GitHubPRPayload,
    create_action_unit,
    redact_secrets,
    security_audit_action_result,
    ENTANGLEMENT_SCHEMA_PENALTY,
)
from .headhunter import (
    HeadhunterProtocol,
    TalentProfile,
    SandboxTalentResult,
    HeadhunterDecision,
)

__all__ = [
    "ExecutionMetrics",
    "Agent",
    "BossAgent",
    "AgentStatus",
    "Blackboard",
    "TaskRequest",
    "FlowUnit",
    "Charter",
    "CharterState",
    "FlowChartCharterSystem",
    "fitness",
    "fitness_components",
    "speed_score",
    "token_bloat_penalty",
    "reference_node_fitness",
    "risk_from_fitness",
    "COST_NORM",
    "INDUSTRY_BENCHMARK",
    "StrategyVector",
    "BudgetVector",
    "GovernanceVector",
    "OpsVector",
    "RhythmAudit",
    "validate_executive_payload",
    "CEOAgent",
    "CFOAgent",
    "BoardAgent",
    "RhythmValidatorAgent",
    "ExecutiveBoard",
    "KnowledgeGraph",
    "TextUnit",
    "ingest_text",
    "run_reindex_loop",
    "extract_triples",
    "verify_extraction",
    "bind_episode",
    "LiveModel",
    "detect_live_provider",
    "run_system_audit",
    "format_audit_report",
    "issue_receipt",
    "verify_receipt",
    "verify_chain",
    "build_ontology",
    "FOUNDATIONS",
    "foundations_table",
    "blueprint_export",
    "FLOW_UNIT_BLUEPRINT",
    "QuantumRouter",
    "quantum_path_select",
    "build_superposition",
    "measure",
    "reinforce",
    "entanglement_score",
    "contextual_entropy",
    "apply_cfo_budget_matrix",
    "SuperpositionState",
    "PathAmplitude",
    "MeasurementRecord",
    "DEFAULT_PATHS",
    "PATH_STANDARD",
    "PATH_CLEANSING",
    "PATH_LITE",
    "synergy_score",
    "structural_divergence",
    "handoff_synergy",
    "mean_pair_synergy",
    "AgentSkillRuntime",
    "MuscleMemoryStore",
    "MuscleMemoryRecord",
    "RosterAction",
    "init_boss_agent",
    "BOSS_AGENT_SYSTEM_PROMPT",
    "BOSS_ACKNOWLEDGEMENT",
    "AGENT_SKILL_SCHEMAS",
    "TypedFlowUnit",
    "AgentFitness",
    "ReferenceQuantumRouter",
    "WorkerAgent",
    "ReferenceBossAgent",
    "CFOHaltError",
    "default_playbook",
    "run_reference_simulation",
    "apply_reference_telemetry",
    "ExecutionMemoryRecord",
    "MuscleMemoryVectorDB",
    "encode_state",
    "cosine_similarity",
    "seed_legacy_refactor",
    "run_muscle_memory_simulation",
    "SurvivalStatus",
    "GenerationParameters",
    "LedgerEntry",
    "TelemetryLedger",
    "LeanRehireDecision",
    "build_worker_system_prompt",
    "generation_params_for_risk",
    "risk_from_ledger",
    "lean_rehire_check",
    "should_fire_from_ledger",
    "ElasticRequisitionBoard",
    "PhantomRecord",
    "LivingPlaybook",
    "AscendedMemoryRecord",
    "AbstractedKPIs",
    "seed_living_playbook",
    "objective_signature_from_payload",
    "capability_map_from_path",
    "AnalyticsChief",
    "RosterRecommendationDossier",
    "DailyTelemetrySnapshot",
    "AgentTrend",
    "CheatCodeExtraction",
    "WORKWEEK_DAYS",
    "LLMBridge",
    "LLMNodeOutput",
    "LLMBridgeConfig",
    "SamplingParams",
    "ProviderUsage",
    "resolve_provider_key",
    "LLMExecutionClient",
    "LLMExecutionRequest",
    "LLMExecutionResponse",
    "FlowUnitResultSchema",
    "validate_llm_output",
    "ProductionMuscleMemory",
    "EmbeddingProvider",
    "run_workers_parallel",
    "WorkerTask",
    "WorkerNode",
    "SimulationSandbox",
    "ScenarioSandbox",
    "HarnessKernel",
    "KillSwitch",
    "KillSwitchError",
    "ToolPort",
    "ExecutionSandbox",
    "SandboxPolicy",
    "DurableNotebook",
    "bind_kill_law",
    "refuse_side_effect",
    "run_phase2_sandbox",
    "PlaybookCompiler",
    "CompiledPlaybook",
    "compile_playbook",
    "generate_pydantic_model",
    "hydrate_system",
    "run_compiled_playbook",
    "get_metrics_hub",
    "MetricsHub",
    # v1.7 Hybrid Knowledge Expansion
    "HybridBossRouter",
    "RouteLane",
    "RouteDecision",
    "MultiHopReasoner",
    "HopSchema",
    "MultiHopResultSchema",
    "LazyGlobalSynthesisSquad",
    "GlobalSynthesisReport",
    "CommunityMapResult",
    "SynthesisSquadMember",
    # v1.8 Autonomous Scaling Horizon
    "SwarmManager",
    "SwarmItemSchema",
    "SwarmItemResultSchema",
    "SwarmReportSchema",
    "TokenLedger",
    "HeadhunterProtocol",
    "TalentProfile",
    "SandboxTalentResult",
    "HeadhunterDecision",
    # v2.0 Hands of the Corporation
    "ActionUnit",
    "ActionUnit_SlackWebhook",
    "ActionUnit_GitHubPR",
    "ActionResult",
    "SlackWebhookPayload",
    "GitHubPRPayload",
    "create_action_unit",
    "redact_secrets",
    "security_audit_action_result",
    "ENTANGLEMENT_SCHEMA_PENALTY",
    # v2.1 Coach Trust
    "CharterSynthesizer",
    "CharterDraft",
    "CharterDraftStatus",
    "SynthesizedCharterSchema",
    "audit_cfo_ceiling",
    "seed_synthesis_memories",
    "validate_synthesized_unit",
    # v2.2 Ironclad
    "SecretScrubber",
    "StatePersisterVault",
    "scrub_payload",
    "TenantNamespacedEngine",
    "TenantRegistry",
    "get_tenant_registry",
    "resolve_tenant_id",
    "RhythmViolationError",
    "ForceQualityForbidden",
    "EvidenceBundle",
    "build_rhythm_audit",
    "independent_audit",
    "earned_quality",
    "collect_evidence",
    "enforce_rhythm_or_raise",
    "marker_for_unit",
    "list_providers",
    "run_golden_evals",
    "DEFAULT_GOLDEN_TASKS",
    "run_live_goldens",
    "RetrievalPort",
    "RetrievalResult",
    "RetrievalHit",
]


_REEXPORT_FITNESS = (DEFAULT_ALPHA, DEFAULT_BETA, DEFAULT_GAMMA, DEFAULT_DELTA)
__version__ = "3.3.0"
