"""FlowChartCharter core — execution-and-quality-first multi-agent state-charts."""

from .metrics import ExecutionMetrics
from .agents import Agent, BossAgent, AgentStatus, WorkerNode
from .blackboard import Blackboard, TaskRequest
from .charter import FlowUnit, Charter, CharterState
from .system import FlowChartCharterSystem
from .fitness import (
    fitness,
    fitness_components,
    speed_score,
    token_bloat_penalty,
    reference_node_fitness,
    risk_from_fitness,
    DEFAULT_ALPHA,
    DEFAULT_BETA,
    DEFAULT_GAMMA,
    DEFAULT_DELTA,
    COST_NORM,
    INDUSTRY_BENCHMARK,
)
from .vectors import (
    StrategyVector,
    BudgetVector,
    GovernanceVector,
    OpsVector,
    RhythmAudit,
    validate_executive_payload,
)
from .executive import (
    CEOAgent,
    CFOAgent,
    BoardAgent,
    RhythmValidatorAgent,
    ExecutiveBoard,
)
from .knowledge_graph import KnowledgeGraph, build_ontology
from .foundations import (
    FOUNDATIONS,
    foundations_table,
    blueprint_export,
    FLOW_UNIT_BLUEPRINT,
)
from .quantum import (
    QuantumRouter,
    quantum_path_select,
    build_superposition,
    measure,
    reinforce,
    entanglement_score,
    contextual_entropy,
    apply_cfo_budget_matrix,
    SuperpositionState,
    PathAmplitude,
    MeasurementRecord,
    DEFAULT_PATHS,
    PATH_STANDARD,
    PATH_CLEANSING,
    PATH_LITE,
)
from .synergy import (
    synergy_score,
    structural_divergence,
    handoff_synergy,
    mean_pair_synergy,
)
from .skills import (
    AgentSkillRuntime,
    MuscleMemoryStore,
    MuscleMemoryRecord,
    RosterAction,
    init_boss_agent,
)
from .prompts import (
    BOSS_AGENT_SYSTEM_PROMPT,
    BOSS_ACKNOWLEDGEMENT,
    AGENT_SKILL_SCHEMAS,
)
from .reference_engine import (
    TypedFlowUnit,
    AgentFitness,
    ReferenceQuantumRouter,
    WorkerAgent,
    BossAgent as ReferenceBossAgent,
    CFOHaltError,
    default_playbook,
    run_reference_simulation,
    apply_reference_telemetry,
)
from .muscle_memory import (
    ExecutionMemoryRecord,
    MuscleMemoryVectorDB,
    encode_state,
    cosine_similarity,
    seed_legacy_refactor,
    run_muscle_memory_simulation,
)
from .survival import (
    SurvivalStatus,
    GenerationParameters,
    LedgerEntry,
    TelemetryLedger,
    LeanRehireDecision,
    build_worker_system_prompt,
    generation_params_for_risk,
    risk_from_ledger,
    lean_rehire_check,
    should_fire_from_ledger,
)
from .elastic import ElasticRequisitionBoard, PhantomRecord
from .living_playbook import (
    LivingPlaybook,
    AscendedMemoryRecord,
    AbstractedKPIs,
    seed_living_playbook,
    objective_signature_from_payload,
    capability_map_from_path,
)
from .llm_bridge import LLMBridge, LLMNodeOutput, LLMBridgeConfig
from .simulation_sandbox import SimulationSandbox, run_phase2_sandbox
from .playbook_compiler import (
    PlaybookCompiler,
    CompiledPlaybook,
    compile_playbook,
    generate_pydantic_model,
    hydrate_system,
    run_compiled_playbook,
)
from .production import (
    LLMExecutionClient,
    LLMExecutionRequest,
    LLMExecutionResponse,
    FlowUnitResultSchema,
    validate_llm_output,
    ProductionMuscleMemory,
    EmbeddingProvider,
    run_workers_parallel,
    WorkerTask,
)
from .analytics import (
    AnalyticsChief,
    RosterRecommendationDossier,
    DailyTelemetrySnapshot,
    AgentTrend,
    CheatCodeExtraction,
    WORKWEEK_DAYS,
)

__all__ = [
    "ExecutionMetrics",
    "Agent",
    "BossAgent",
    "AgentStatus",
    "Blackboard",
    "TaskRequest",
    "FlowUnit",
    "Charter",
    "CharterState",
    "FlowChartCharterSystem",
    "fitness",
    "fitness_components",
    "speed_score",
    "token_bloat_penalty",
    "reference_node_fitness",
    "risk_from_fitness",
    "COST_NORM",
    "INDUSTRY_BENCHMARK",
    "StrategyVector",
    "BudgetVector",
    "GovernanceVector",
    "OpsVector",
    "RhythmAudit",
    "validate_executive_payload",
    "CEOAgent",
    "CFOAgent",
    "BoardAgent",
    "RhythmValidatorAgent",
    "ExecutiveBoard",
    "KnowledgeGraph",
    "build_ontology",
    "FOUNDATIONS",
    "foundations_table",
    "blueprint_export",
    "FLOW_UNIT_BLUEPRINT",
    "QuantumRouter",
    "quantum_path_select",
    "build_superposition",
    "measure",
    "reinforce",
    "entanglement_score",
    "contextual_entropy",
    "apply_cfo_budget_matrix",
    "SuperpositionState",
    "PathAmplitude",
    "MeasurementRecord",
    "DEFAULT_PATHS",
    "PATH_STANDARD",
    "PATH_CLEANSING",
    "PATH_LITE",
    "synergy_score",
    "structural_divergence",
    "handoff_synergy",
    "mean_pair_synergy",
    "AgentSkillRuntime",
    "MuscleMemoryStore",
    "MuscleMemoryRecord",
    "RosterAction",
    "init_boss_agent",
    "BOSS_AGENT_SYSTEM_PROMPT",
    "BOSS_ACKNOWLEDGEMENT",
    "AGENT_SKILL_SCHEMAS",
    "TypedFlowUnit",
    "AgentFitness",
    "ReferenceQuantumRouter",
    "WorkerAgent",
    "ReferenceBossAgent",
    "CFOHaltError",
    "default_playbook",
    "run_reference_simulation",
    "apply_reference_telemetry",
    "ExecutionMemoryRecord",
    "MuscleMemoryVectorDB",
    "encode_state",
    "cosine_similarity",
    "seed_legacy_refactor",
    "run_muscle_memory_simulation",
    "SurvivalStatus",
    "GenerationParameters",
    "LedgerEntry",
    "TelemetryLedger",
    "LeanRehireDecision",
    "build_worker_system_prompt",
    "generation_params_for_risk",
    "risk_from_ledger",
    "lean_rehire_check",
    "should_fire_from_ledger",
    "ElasticRequisitionBoard",
    "PhantomRecord",
    "LivingPlaybook",
    "AscendedMemoryRecord",
    "AbstractedKPIs",
    "seed_living_playbook",
    "objective_signature_from_payload",
    "capability_map_from_path",
    "AnalyticsChief",
    "RosterRecommendationDossier",
    "DailyTelemetrySnapshot",
    "AgentTrend",
    "CheatCodeExtraction",
    "WORKWEEK_DAYS",
    "LLMBridge",
    "LLMNodeOutput",
    "LLMBridgeConfig",
    "LLMExecutionClient",
    "LLMExecutionRequest",
    "LLMExecutionResponse",
    "FlowUnitResultSchema",
    "validate_llm_output",
    "ProductionMuscleMemory",
    "EmbeddingProvider",
    "run_workers_parallel",
    "WorkerTask",
    "WorkerNode",
    "SimulationSandbox",
    "run_phase2_sandbox",
    "PlaybookCompiler",
    "CompiledPlaybook",
    "compile_playbook",
    "generate_pydantic_model",
    "hydrate_system",
    "run_compiled_playbook",
]


_REEXPORT_FITNESS = (DEFAULT_ALPHA, DEFAULT_BETA, DEFAULT_GAMMA, DEFAULT_DELTA)
__version__ = "1.4.0"
